package info.shelfunit.shiro

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class ShiroSecurityFilters {
    def filters = {
        
        base(uri: "/") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
            }
        } 
        
        
        movieView(controller: "movie", action: "(index|list|show)") {
            before = {
                return true
                accessControl { true }
            }
        }
        
        // we want anyone to see the info for all movies (index) and for any one movie (show)
        movieChange(controller: "movie", action: "(create|edit|save|update|delete)") {
            before = {
                // accessControl(auth: true) { true }
                accessControl {
                    permission("movie:$actionName")
                }
            }
        }
        /*
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true

                // Access control by convention.
                accessControl()
            }
        }
        */
    }
}

